function [net] = train_simple_lstm(xTrain, yTrain)

[rrr,ccc] = size(xTrain{1});

numResponses = 2;
featureDimension = rrr; %1;
%
%numHiddenUnits = 100;
maxEpochs       = 500; %150 ; %150; %500; %1000
miniBatchSize   = 200; %200;%200;

Networklayers = [sequenceInputLayer(featureDimension, "Normalization","zscore") ...
    lstmLayer(128) ...
    fullyConnectedLayer(numResponses) ...
    regressionLayer];
options = trainingOptions('adam', ...
                'MaxEpochs',maxEpochs, ...
                'MiniBatchSize',miniBatchSize, ...
                'GradientThreshold',10, ...
                'SequenceLength','longest', ...             % padding
                'SequencePaddingDirection', 'right', ...    %
                'SequencePaddingValue',0, ...               %
                'Shuffle','once', ...
                'Plots','training-progress',...
                'LearnRateSchedule','piecewise',...
                'LearnRateDropPeriod',200,... %was 100
                'Verbose',1);%,...
net = trainNetwork(xTrain,yTrain,Networklayers,options);
